### ISSUE TITLE
Exception after upgrading from 1.0.5 to 1.0.8

### ISSUE THREAD

**Issue by klickreflex** [jedamzik/statamic-toc#4]
After upgrading ToC to 1.0.8 I'm getting the following error when trying to open entries of _one_ of my collections in the CP (not on any other collection).

```
Carbon\Exceptions\InvalidFormatException
Unexpected data found. Unexpected data found. The separation symbol could not be found Data missing
```

Here's the info about the the affected collection, if that helps:

Collection
```yaml
title: Events
sites:
  - de
  - en
propagate: false
template: default
layout: layout
revisions: false
sort_dir: asc
date_behavior:
  past: public
  future: private
```

Collection Blueprint
```yaml
title: Event
sections:
  main:
    display: Hauptteil
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        import: event
      -
        handle: service_relation
        field:
          max_items: 1
          mode: default
          create: false
          collections:
            - pages
          display: 'Zugehöriges Angebot'
          type: entries
          icon: entries
          listable: hidden
          instructions_position: above
          validate:
            - required
      -
        handle: prevention_category
        field:
          max_items: 1
          mode: select
          create: false
          taxonomies:
            - preventions
          display: Präventions-Bereich
          type: terms
          icon: taxonomy
          listable: hidden
          instructions_position: above
      -
        handle: info
        field:
          always_show_set_button: false
          buttons:
            - h3
            - bold
            - unorderedlist
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: 'Weitere Informationen'
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
      -
        handle: inquiry_form
        field:
          max_items: 1
          default: booking_inquiry
          display: Formular
          type: form
          icon: form
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required

```

Imported fieldset `event`

```yaml
title: Veranstaltung
fields:
  -
    handle: all_day
    field:
      type: toggle
      width: 25
      display: 'Ganztägig?'
  -
    handle: multi_day
    field:
      type: toggle
      width: 25
      display: 'Mehrtägig?'
  -
    handle: start_date
    field:
      type: date
      allow_blank: false
      allow_time: false
      require_time: false
      earliest_date: 'January 1, 1900'
      input_format: M/D/YYYY
      width: 33
      display: 'Anfangsdatum'
      if:
        multi_day: 'equals false'
  -
    handle: start_time
    field:
      type: time
      width: 33
      display: 'Anfangszeit'
      if:
        multi_day: 'equals false'
        all_day: 'equals false'
  -
    handle: end_time
    field:
      type: time
      width: 33
      display: 'Endzeit'
      if:
        multi_day: 'equals false'
        all_day: 'equals false'
  -
    handle: days
    field:
      type: grid
      mode: table
      fields:
        -
          handle: date
          field:
            type: date
            allow_blank: false
            allow_time: false
            require_time: false
            input_format: M/D/YYYY
            earliest_date: 'January 1, 1900'
            width: 33
            display: Datum
        -
          handle: start_time
          field:
            type: time
            width: 33
            display: 'Anfangszeit'
        -
          handle: end_time
          field:
            type: time
            width: 33
            display: 'Endzeit'
      display: Tage
      min_rows: 2
      add_row: 'Tag hinzufügen'
      listable: hidden
      reorderable: true
      if:
        multi_day: 'equals true'
  -
    handle: recurrence_section
    field:
      type: section
      display: Wiederholung
      if:
        multi_day: 'equals false'
  -
    handle: recurrence
    field:
      type: select
      options:
        0: Keine
        daily: täglich
        weekly: wöchentlich
        monthly: monatlich
        every: alle
      width: 25
      display: 'Art der Wiederholung'
      default: false
      if:
        multi_day: 'equals false'
  -
    handle: interval
    field:
      type: integer
      width: 25
      display: Intervall
      if:
        recurrence: 'equals every'
  -
    handle: period
    field:
      type: select
      options:
        days: Tage
        weeks: Wochen
        years: Jahre
      display: Zeitraum
      width: 25
      if:
        recurrence: 'equals every'
  -
    handle: end_date
    field:
      type: date
      allow_blank: true
      allow_time: false
      require_time: false
      earliest_date: 'January 1, 1900'
      input_format: M/D/YYYY
      display: 'Enddatum'
      width: 25
      listable: hidden
      mode: single
      time_enabled: false
      time_required: false
      full_width: false
      inline: false
      columns: 1
      rows: 1
      if:
        recurrence: 'contains_any daily, weekly, monthly, every'

```
